trigger:
  tags:
    include:
      - "v*"
  branches:
    exclude:
      - "*"

pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: "Release"

steps:
  - task: UseDotNet@2
    displayName: "Use .Net Core SDK 7.x"
    inputs:
      packageType: "sdk"
      version: "7.x"
      includePreviewVersions: false

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo '{
            "parallelizeAssembly": false,
            "parallelizeTestCollections": false,
            "diagnosticMessages": false
        }' > Tests/IntegrationTests/FastEndpoints/xunit.runner.json

  - task: DotNetCoreCLI@2
    displayName: "Run Tests"
    inputs:
      command: "test"
      projects: "Tests/**/*.csproj"
      arguments: "--configuration $(BuildConfiguration)"
      workingDirectory: "Tests"